[pytest]
addopts = --no-header --html=report.html --base-url https://myacl.acldigital.com/ --tracing retain-on-failure --headed --browser chromium --screenshot on --video retain-on-failure 
testpaths = tests